### ISSUE TITLE
Replacing array displays empty rows or moves client scroll position

### ISSUE THREAD

**Issue by reft** [aurelia/ui-virtualization#126]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.2.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.9.1

* **NPM Version:**
5.5.1

* **Browser:**
Chrome

* **Language:**
TypeScript >=1.9.0-dev || ^2.0.0

**Current behavior:**
Adding items to the array works as expected:

this.myArray = this.myArray.concat(result);

But when you replace the array it often displays empty rows OR move the client scroll position to a different height. Empty rows are removed/fixed if you scroll up/down. I'm using infinite scroll, maybe it has something to do with this?

this.myArray = result;

**Expected/desired behavior:**
Should not display empty rows or move users scroll position when replacing array.

* **What is the motivation / use case for changing the behavior?**
When you update something in the array, send the data to the api and update, and then return the data you want to update the client array, (replace), with the data from the api, (client needs to see the row is updated and the values changed). If you can't update the entire array you force me to update each row manually on the client side.

**Comment by reft** [comment]
Empty rows:

![image](https://user-images.githubusercontent.com/3218213/35066097-c132ab24-fbcf-11e7-8cd0-932f7eb95f1e.png)

**Comment by bigopon** [comment]
@reft Do you have a simple repro repo / gist I can look at ?

**Comment by reft** [comment]
@bigopon It's a private repo so I don't have anything atm but I can probably throw together an example later tonight or tomorrow.

It should not be hard to reproduce the problem.

1. Use a table with 200+ rows.
2. Scroll down to a scroll position
3. Onclick event on table row that replaces the array, this.myArray = new array [] (Should be same data/size but perhaps with some properties changed)
4. Continue testing with different scroll position. I've found that the most problems occur when ur at the bottom of the table

You should now see empty rows displayed and/or the scroll position moved.

**Comment by bigopon** [comment]
That case is already addressed in the fix in my other PR. Can you use that fix and update me ? You can simply go to the gist in that pr, copy the entire ui virtualization file and use it locally instead updating the node module

**Comment by reft** [comment]
@bigopon You mean this file, ui-virtualziation.js?

https://gist.run/?id=f12e45770938f3ffa14b713d69cdcb71

I'm not sure where to put this file, I'm currently using: node_modules\aurelia-ui-virtualization\dist\amd\aurelia-ui-virtualization.js

**Comment by reft** [comment]
@bigopon I'm unable to test your files locally using typescript, I'm getting: 

GET http://localhost:3000/client/aurelia-ui-virtualization.js net::ERR_ABORTED

It did however load when i tried the files in a new project without TS... 
Changing .js files to .ts gives me a ton of build errors.

**Comment by bigopon** [comment]
the transpiled js is here https://gist.github.com/bigopon/f12e45770938f3ffa14b713d69cdcb71#file-virtual-repeat-transpiled-js (I ran it through typescript transpiler at https://typescriptlang.org/playground)

How to load this, please have a a look at the gist @reft

**Comment by reft** [comment]
@bigopon Thank you, got it working now but the problems remain..

**Comment by bigopon** [comment]
Ok I see, the issue happens when you are at the bottom. and replace existing by a new array with the same length. I think it should be addressed in another PR

**Comment by reft** [comment]
@bigopon  I think I found the problem..

![capture](https://user-images.githubusercontent.com/3218213/36054961-81047014-0df9-11e8-832e-e990268eed37.PNG)

The array before and after does not have the same format

*Correction, image on the left is from the api response and image on the right is from the current displayed array before update.

@bigopon It has something to do with binding right, how do you make the api response look the same as the current displayed array?

**Comment by reft** [comment]
I found a workaround, instead of doing this:

```
myArray = newArray;
```

I can do:

```
myArray.splice(0, myArray.length);

myArray.forEach(function (item) {
    myArray.push(item);
});
```

I no longer get empty rows and the scroll position doesn't move :)

**Comment by bigopon** [comment]
@reft yes it's the getter / setter set by binding system to detect changes. so your array is still there. Glad you got it working, but make sure you migrate to the new version once the fix for that ready 😄

**Comment by reft** [comment]
@bigopon It seems like table with aurelia-virtuaization is still bugged.

I have opened another issue that is somewhat connected with this issue.

https://github.com/aurelia/ui-virtualization/issues/128

I have also tried your gist version but it did not help..
